/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BacktestConfig {
  'endDate' : Time,
  'asset' : TickerSymbol,
  'strategyName' : string,
  'startDate' : Time,
}
export interface BacktestResult {
  'returnPercent' : number,
  'maxDrawdownPercent' : number,
  'config' : BacktestConfig,
}
export interface BuyOrder {
  'tickerSymbol' : TickerSymbol,
  'quantity' : bigint,
  'price' : number,
}
export type NoteContent = string;
export interface Portfolio {
  'trades' : Array<Trade>,
  'cashBalance' : number,
  'positions' : Array<Position>,
}
export interface Position {
  'avgPrice' : number,
  'tickerSymbol' : TickerSymbol,
  'quantity' : bigint,
}
export interface SellOrder {
  'tickerSymbol' : TickerSymbol,
  'quantity' : bigint,
  'price' : number,
}
export type TickerSymbol = string;
export type Time = bigint;
export interface Trade {
  'tickerSymbol' : TickerSymbol,
  'timestamp' : Time,
  'quantity' : bigint,
  'price' : number,
}
export interface _SERVICE {
  'addToWatchlist' : ActorMethod<[string], undefined>,
  'createOrUpdateNote' : ActorMethod<[TickerSymbol, NoteContent], NoteContent>,
  'createPortfolio' : ActorMethod<[], Portfolio>,
  'getNotes' : ActorMethod<[Principal], Array<[TickerSymbol, NoteContent]>>,
  'getPortfolio' : ActorMethod<[], Portfolio>,
  'getWatchlist' : ActorMethod<
    [],
    { 'size' : bigint, 'watchlist' : Array<string> }
  >,
  'placeBuyOrder' : ActorMethod<[BuyOrder], Portfolio>,
  'placeSellOrder' : ActorMethod<[SellOrder], Portfolio>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'saveBacktestResult' : ActorMethod<[BacktestResult], Array<BacktestResult>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];