/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TickerSymbol = IDL.Text;
export const NoteContent = IDL.Text;
export const Time = IDL.Int;
export const Trade = IDL.Record({
  'tickerSymbol' : TickerSymbol,
  'timestamp' : Time,
  'quantity' : IDL.Int,
  'price' : IDL.Float64,
});
export const Position = IDL.Record({
  'avgPrice' : IDL.Float64,
  'tickerSymbol' : TickerSymbol,
  'quantity' : IDL.Int,
});
export const Portfolio = IDL.Record({
  'trades' : IDL.Vec(Trade),
  'cashBalance' : IDL.Float64,
  'positions' : IDL.Vec(Position),
});
export const BuyOrder = IDL.Record({
  'tickerSymbol' : TickerSymbol,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const SellOrder = IDL.Record({
  'tickerSymbol' : TickerSymbol,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const BacktestConfig = IDL.Record({
  'endDate' : Time,
  'asset' : TickerSymbol,
  'strategyName' : IDL.Text,
  'startDate' : Time,
});
export const BacktestResult = IDL.Record({
  'returnPercent' : IDL.Float64,
  'maxDrawdownPercent' : IDL.Float64,
  'config' : BacktestConfig,
});

export const idlService = IDL.Service({
  'addToWatchlist' : IDL.Func([IDL.Text], [], []),
  'createOrUpdateNote' : IDL.Func(
      [TickerSymbol, NoteContent],
      [NoteContent],
      [],
    ),
  'createPortfolio' : IDL.Func([], [Portfolio], []),
  'getNotes' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Tuple(TickerSymbol, NoteContent))],
      ['query'],
    ),
  'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
  'getWatchlist' : IDL.Func(
      [],
      [IDL.Record({ 'size' : IDL.Nat, 'watchlist' : IDL.Vec(IDL.Text) })],
      ['query'],
    ),
  'placeBuyOrder' : IDL.Func([BuyOrder], [Portfolio], []),
  'placeSellOrder' : IDL.Func([SellOrder], [Portfolio], []),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  'saveBacktestResult' : IDL.Func(
      [BacktestResult],
      [IDL.Vec(BacktestResult)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TickerSymbol = IDL.Text;
  const NoteContent = IDL.Text;
  const Time = IDL.Int;
  const Trade = IDL.Record({
    'tickerSymbol' : TickerSymbol,
    'timestamp' : Time,
    'quantity' : IDL.Int,
    'price' : IDL.Float64,
  });
  const Position = IDL.Record({
    'avgPrice' : IDL.Float64,
    'tickerSymbol' : TickerSymbol,
    'quantity' : IDL.Int,
  });
  const Portfolio = IDL.Record({
    'trades' : IDL.Vec(Trade),
    'cashBalance' : IDL.Float64,
    'positions' : IDL.Vec(Position),
  });
  const BuyOrder = IDL.Record({
    'tickerSymbol' : TickerSymbol,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const SellOrder = IDL.Record({
    'tickerSymbol' : TickerSymbol,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const BacktestConfig = IDL.Record({
    'endDate' : Time,
    'asset' : TickerSymbol,
    'strategyName' : IDL.Text,
    'startDate' : Time,
  });
  const BacktestResult = IDL.Record({
    'returnPercent' : IDL.Float64,
    'maxDrawdownPercent' : IDL.Float64,
    'config' : BacktestConfig,
  });
  
  return IDL.Service({
    'addToWatchlist' : IDL.Func([IDL.Text], [], []),
    'createOrUpdateNote' : IDL.Func(
        [TickerSymbol, NoteContent],
        [NoteContent],
        [],
      ),
    'createPortfolio' : IDL.Func([], [Portfolio], []),
    'getNotes' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Tuple(TickerSymbol, NoteContent))],
        ['query'],
      ),
    'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
    'getWatchlist' : IDL.Func(
        [],
        [IDL.Record({ 'size' : IDL.Nat, 'watchlist' : IDL.Vec(IDL.Text) })],
        ['query'],
      ),
    'placeBuyOrder' : IDL.Func([BuyOrder], [Portfolio], []),
    'placeSellOrder' : IDL.Func([SellOrder], [Portfolio], []),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
    'saveBacktestResult' : IDL.Func(
        [BacktestResult],
        [IDL.Vec(BacktestResult)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };