/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type NoteContent = string;
export interface SellOrder {
    tickerSymbol: TickerSymbol;
    quantity: bigint;
    price: number;
}
export type Time = bigint;
export interface Position {
    avgPrice: number;
    tickerSymbol: TickerSymbol;
    quantity: bigint;
}
export interface BacktestResult {
    returnPercent: number;
    maxDrawdownPercent: number;
    config: BacktestConfig;
}
export interface Trade {
    tickerSymbol: TickerSymbol;
    timestamp: Time;
    quantity: bigint;
    price: number;
}
export type TickerSymbol = string;
export interface Portfolio {
    trades: Array<Trade>;
    cashBalance: number;
    positions: Array<Position>;
}
export interface BacktestConfig {
    endDate: Time;
    asset: TickerSymbol;
    strategyName: string;
    startDate: Time;
}
export interface BuyOrder {
    tickerSymbol: TickerSymbol;
    quantity: bigint;
    price: number;
}
export interface backendInterface {
    addToWatchlist(symbol: string): Promise<void>;
    createOrUpdateNote(tickerSymbol: TickerSymbol, content: NoteContent): Promise<NoteContent>;
    createPortfolio(): Promise<Portfolio>;
    getNotes(caller: Principal): Promise<Array<[TickerSymbol, NoteContent]>>;
    getPortfolio(): Promise<Portfolio>;
    getWatchlist(): Promise<{
        size: bigint;
        watchlist: Array<string>;
    }>;
    placeBuyOrder(order: BuyOrder): Promise<Portfolio>;
    placeSellOrder(order: SellOrder): Promise<Portfolio>;
    removeFromWatchlist(symbol: string): Promise<void>;
    saveBacktestResult(result: BacktestResult): Promise<Array<BacktestResult>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0);
            return result;
        }
    }
    async createOrUpdateNote(arg0: TickerSymbol, arg1: NoteContent): Promise<NoteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateNote(arg0, arg1);
            return result;
        }
    }
    async createPortfolio(): Promise<Portfolio> {
        if (this.processError) {
            try {
                const result = await this.actor.createPortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPortfolio();
            return result;
        }
    }
    async getNotes(arg0: Principal): Promise<Array<[TickerSymbol, NoteContent]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes(arg0);
            return result;
        }
    }
    async getPortfolio(): Promise<Portfolio> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolio();
            return result;
        }
    }
    async getWatchlist(): Promise<{
        size: bigint;
        watchlist: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return result;
        }
    }
    async placeBuyOrder(arg0: BuyOrder): Promise<Portfolio> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBuyOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBuyOrder(arg0);
            return result;
        }
    }
    async placeSellOrder(arg0: SellOrder): Promise<Portfolio> {
        if (this.processError) {
            try {
                const result = await this.actor.placeSellOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeSellOrder(arg0);
            return result;
        }
    }
    async removeFromWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
    async saveBacktestResult(arg0: BacktestResult): Promise<Array<BacktestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBacktestResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBacktestResult(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
